### ISSUE TITLE
PLEASE DELETE THIS REPOSITORY, I don't want to see it in my repositories anymore

### ISSUE THREAD

**Issue by Seluj78** [Nacorpio/Life-Engine#2]
PLEASE DELETE THIS REPOSITORY, I don't want to see it in my repositories anymore

**Comment by Nacorpio** [comment]
I really don't give a shit.

**Comment by Seluj78** [comment]
Well then could you just delete the repository or remove me from it please ?

**Comment by Nacorpio** [comment]
No.

**Comment by Seluj78** [comment]
Why wouldn't you ?
